### PR TITLE
Webpack starter template and List structure

### PR DESCRIPTION
**Pull request by ticoniq**
Create the webpack starter template and added the list structure.

The following changes have been made:

- A new tasks array has been added to the project.

Each task in the tasks array is an object with the following properties:
> 1. Description: A string that describes the task.
> 2. Completed: A boolean value that shows whether the task is completed.
> 3. Index: A number that shows the order of the task on the list.

- A new function called displayTask() has been added to the project. This function iterates over the tasks array and renders each task as an HTML list item element.
- The DOMContentLoaded event has been listened for and the displayTask() function has been called when this event fires. This ensures that the tasks are rendered when the page loads.

### CODE REVIEW

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ticoniq,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that does not have the Future Features section in the README. Kindly add the section and its link on the Table of Contents.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @ticoniq 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️   Created array of simple todo tasks ✅ 


## Required Changes ♻️

- [ ] Kindly make sure that  Webpack dev server is set up and running with no errors, currently when I run `npm run dev ` or `npm start`  I can't see your application, please ensure you can see the arrays of todo created 👍🏿 
Screenshot_63


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ticoniq** [comment]
@prolajumokeoni it's working 
Screenshot (130)

**Comment by prolajumokeoni** [comment]
Hi @ticoniq, thank you for pointing this out, I just noticed that on my `http://localhost:3000/` another code was running, after restarting my PC, I see that your app works, I apologize for any inconvenience, thanks for reaching out
 
Screenshot_64

**Pull request merged**
